name       : libass
version    : 0.14.0
release    : 8
source     :
    - https://github.com/libass/libass/releases/download/0.14.0/libass-0.14.0.tar.xz : 881f2382af48aead75b7a0e02e65d88c5ebd369fe46bc77d9270a94aa8fd38a2
license    : ISC
component  : multimedia.library
summary    : Portable subtitle renderer
description: |
    Libass is a portable library for SSA/ASS subtitles rendering.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
