name        : libass
version     : 0.12.1
release     : 4
source     :
    - https://github.com/libass/libass/releases/download/0.12.1/libass-0.12.1.tar.xz : 87864517e482e94130864ad9e4217c3925119e8cc0c1509133989997a61592d7
license     :
    - ISC
summary     : Portable subtitle renderer
builddeps   :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(fontconfig)
    - pkgconfig(harfbuzz)
    - pkgconfig(libpng)
    - pkgconfig(enca)
    - yasm
description : |
    Portable subtitle renderer
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
