name       : libass
version    : 0.15.2
release    : 12
source     :
    - https://github.com/libass/libass/releases/download/0.15.2/libass-0.15.2.tar.xz : 1be2df9c4485a57d78bb18c0a8ed157bc87a5a8dd48c661961c625cb112832fd
license    : ISC
component  : multimedia.library
summary    : Portable subtitle renderer
description: |
    Libass is a portable library for SSA/ASS subtitles rendering.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
