name       : libass
version    : 0.13.4
release    : 7
source     :
    - https://github.com/libass/libass/releases/download/0.13.4/libass-0.13.4.tar.xz : d84a2fc89011b99d87fc47af91906622707c165d1860e9f774825ebbbc9c9fb6
license    : ISC
component  : multimedia.library
summary    : Portable subtitle renderer
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(harfbuzz)
    - pkgconfig(libpng)
    - yasm
description: |
    Portable subtitle renderer
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
