name       : libass
version    : 0.15.1
release    : 11
source     :
    - https://github.com/libass/libass/releases/download/0.15.1/libass-0.15.1.tar.xz : 1cdd39c9d007b06e737e7738004d7f38cf9b1e92843f37307b24e7ff63ab8e53
license    : ISC
component  : multimedia.library
summary    : Portable subtitle renderer
description: |
    Libass is a portable library for SSA/ASS subtitles rendering.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
