name       : libass
version    : 0.17.0
release    : 14
source     :
    - https://github.com/libass/libass/releases/download/0.17.0/libass-0.17.0.tar.xz : 971e2e1db59d440f88516dcd1187108419a370e64863f70687da599fdf66cc1a
license    : ISC
component  : multimedia.library
summary    : Portable subtitle renderer
description: |
    Libass is a portable library for SSA/ASS subtitles rendering.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
    - pkgconfig(libunibreak)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
