name       : libass
version    : 0.13.1
release    : 5
source     :
    - https://github.com/libass/libass/releases/download/0.13.1/libass-0.13.1.tar.xz : 4aa36b1876a61cab46fc9284fee84224b9e2840fe7b3e63d96a8d32574343fe7
license    :
    - ISC
summary    : Portable subtitle renderer
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(fontconfig)
    - pkgconfig(harfbuzz)
    - pkgconfig(libpng)
    - yasm
description: |
    Portable subtitle renderer
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
